# Protection rules for release approval environment
# This ensures manual approval is required before publishing to NuGet

# Required reviewers (you can add specific GitHub usernames)
# reviewers:
#   - your-github-username

# Wait timer (optional - adds a delay before approval)
wait_timer:
  minutes: 0

# Deployment branches (restrict to specific branches)
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false 